### ISSUE TITLE
Separate Transports in projects

### ISSUE THREAD

**Issue by lira92** [Inside-Sistemas/mailer.net#4]
Separate Transports in projects and nuget packages

**Comment by Gimly** [comment]
You would like to have each transport in its own Nuget package? Doesn't that complexify the user experience? What would be the advantage of separating it?

**Comment by lira92** [comment]
Hi @Gimly, I believe Stmp transport could stay in main project, but others transports i think it should be in separate projects, because, in most cases you will use one or two transports (mailgun and smtp or sendgrid and smtp or only smtp), in this way you install only the packages that you need, some transports may have other dependencies. For example, Entity Framework has EntityFramework and EntityFramework.SqlServer.

**Comment by rbj325** [comment]
You can make it work quite nicely with NuGet by using separate .nuspec files.

See Postal.net for an example: https://github.com/andrewdavey/postal/tree/master/build

**Comment by lira92** [comment]
@rbj325 yes, I think we will also need separate csproj files, right?

**Comment by rbj325** [comment]
@lira92 Yes, just add the .csproj to the .sln like you normally would and target it with the .nuspec file to individually release the projects on NuGet.

**Comment by NtFreX** [comment]
Hey I've created a pull request where I seperated the projects. It would be nice if you could take a look and let me know if this is what you expected.
