### ISSUE TITLE
Create Send Async

### ISSUE THREAD

**Issue by lira92** [Inside-Sistemas/mailer.net#5]
Create a method to send email using async, implement on all transports

**Comment by jturinetti** [comment]
Do you want to support asynchronous sending for .NET 4.5 only, or for both .NET 4.0 and 4.5?  4.5 is much simpler given the async / await first-class citizens.  Supporting .NET 4.0 as well introduces more complexity.

**Comment by lira92** [comment]
@jturinetti only .net 4.5.

**Comment by jturinetti** [comment]
I have a branch ready.  Do I need additional privileges to push my branch?

**Comment by jturinetti** [comment]
Nevermind, I need to fork, my mistake.  Will get PR up soon.
